# Generated by Django 2.0.7 on 2018-07-08 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osw', '0002_auto_20180707_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_items', models.IntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('purchase_date', models.DateField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osw.Customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osw.Product')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='purchases',
            field=models.ManyToManyField(through='osw.CustomerProduct', to='osw.Product'),
        ),
    ]
